---
build:
  image: quay.io/buildah/stable
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    #https://github.com/containers/buildah/blob/master/docs/tutorials/03-on-build.md
    BUILDAH_FORMAT: docker
  script:
    - export REGISTRY_AUTH_FILE=${HOME}/auth.json
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - buildah bud -f Dockerfile -t $IMAGE_TAG .
    - CONTAINER_ID=$(buildah from ${IMAGE_TAG})
    - buildah commit --squash $CONTAINER_ID $IMAGE_TAG
    - buildah push $IMAGE_TAG
